# Header
menu:
  Home: /
  Reviews: /reviews
  Resources: /resources
  About: /about
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tagcloud
- archive

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: 'UA-35954107-1'
favicon: /images/favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
